- name:  register domain name
  set_fact:
    domain_name: "{{ item }}"
- name: register logging_server
  set_fact:
     logging_server: "{{ hostvars['access.seinternal.com']['logging_filters'][domain_name] }}"
- debug: var=logging_server

- name: mysql filter table update on relays for logging server
  command: mysql filter -e "update relays set logging_server='{{ new_server }}' where logging_server='{{ old_server }}' and domain='{{ item }}'"
  when: logging_server == old_server
  delegate_to: "{{ master.meta[0] }}"
