---
- name:  register domain name
  set_fact:
    domain_name: "{{ item }}"
- name: register table name (depends on domain name)
  set_fact:
    table: "{{ domain_name | replace('.','_') | replace('-','@002d') }}"

- name: "check domain size"
  shell: "ls -lSh /var/lib/mysql/mx_messages | grep MYD | grep ' {{ table }}' | awk '{print $5}'"
  register: size

- name: "register domain size"
  set_fact:
    size_stdout: "{{ size.stdout_lines[0] }}"

- name: "register report table for domain name"
  set_fact:
      report: "{{ report|default([]) + [ {item:size_stdout} ]  }}"
