---
- name:  "register domain name"
  set_fact:
    domain_name: "{{ item }}"
- name: "register table name (depends on domain name)"
  set_fact:
    table: "{{ domain_name | replace('.','_') | replace('-','@002d') }}"

- name: register logging_server
  set_fact:
     logging_server: "{{ hostvars['access.seinternal.com']['logging_filters'][domain_name] }}"
- debug: var=logging_server

- replace: dest="/tmp/{{ table }}.inmess.sql"  regexp="old_{{ table }}" replace="{{ table }}" backup=yes
- replace: dest="/tmp/{{ table }}.outmess.sql" regexp="old_{{ table }}" replace="{{ table }}" backup=yes

- name: "create database {{ index }} if does not exist"
  command: mysql -e "CREATE DATABASE IF NOT EXISTS {{ index }}"
  when: logging_server == old_server
  loop:
    - mx_messages
    - mx_messages_outgoing
  loop_control:
       loop_var: index

- name: "import table inmess on {{ index }} on target server"
  shell: "mysql mx_messages < /tmp/{{ table }}.inmess.sql"
  register: import_inmess_content
  failed_when: import_inmess_content.rc != 0
  when: logging_server == old_server

- name: "import table outmess on {{ index }} on target server"
  shell: "mysql mx_messages_outgoing < /tmp/{{ table }}.outmess.sql"
  register: import_outmess_content
  failed_when: import_outmess_content.rc != 0
  when: logging_server == old_server
