---
- name:  "register domain name"
  set_fact:
    domain_name: "{{ item }}"
- name: "register table name (depends on domain name)"
  set_fact:
    table: "{{ domain_name | replace('.','_') | replace('-','@002d') }}"

- name: register logging_server
  set_fact:
     logging_server: "{{ hostvars['access.seinternal.com']['logging_filters'][domain_name] }}"
- debug: var=logging_server

- name: "mysql check table backup existence"
  command: mysql -e "SHOW TABLES LIKE 'old_{{ table }}';" "mx_messages"
  register: existence_table_backup

- debug: var=existence_table_backup.stdout

- name: "mysql unlock tables"
  command: mysql -e "UNLOCK TABLES;"
  when: logging_server == old_server and existence_table_backup.stdout != ''

- name: "mysql drop table old-{{ table }} for domain {{ domain_name }}"
  command: mysql -e "DROP TABLE {{ index }}.old_{{ table }};"
  when: logging_server == old_server and existence_table_backup.stdout != ''
  loop:
    - mx_messages
    - mx_messages_outgoing
  loop_control:
       loop_var: index
