---
# 1 - 3. Run api to update hostname confguration
- name: Run api to update hostname confguration
  vars:
      server : "{{ new_hostname.split('.')[0] }}"
      domain : "{{ new_hostname.split(server+'.')[1] }}"
  command: curl -K "https://cluster-api.seinternal.com/api/cluster/{{ domain }}/" -d "{'master:' '\"{{ new_hostname }}\"'}"
# 5. Run the updater
- name: Run the updater
  command: "/home/spamexperts/update/update -d --skip-wait-turn --skip-version-check --skip-apt --skip-restart --skip-cron --skip-applications --skip-pip --skip-pip-cache --skip-preupdate --skip-postupdate --skip-salt --skip-preupdate-migrations --skip-postupdate-migrations"

# 7 - 9. Update database with new entries
- template:
    dest: /root/update_mysql_filter.sql
    src:  update_mysql_filter.j2

- mysql_db:
    state: import
    name: all
    target: /root/update_mysql_filter.sql

# 10. Run python script to generate and update api user password for database using the new hostname as starting point
- name: Running python script
  script: master_script.py

# 11. Restart services so that the configuration loads with new hostname
- name: Services restart
  service:
    name: "{{ item }}"
    state: restarted
  loop:
    - pdns-recursor
    - exim4
    - "exim4-outgoing"
    - "cron"
    - "zabbix-agent"
    - "dovecot"
    - "nginx"
    - "watch_imap"
