---
- hosts: webservers
  become: True
  become_method:  sudo
  become_user:    root
  gather_facts:   true
  vars_files:
    - group_vars/vars.yml
  tasks:
    # --------------------------------------------------------------------------
    # BASICS PREPARATION
    - name: sudoers configuration
      lineinfile: dest=/etc/sudoers state=present
                  regexp='^%sudo' line="{{ item }}"
      with_items:
      - "%sudo ALL=(ALL) NOPASSWD: ALL"

    - name: modules python installation
      raw: "sudo apt-get -y install {{ item }}"
      with_items: ["python", "python-pip"]

    - name: upgrade pip
      pip: name=pip state=latest
      tags:
        - packages
    - name: pip manage dependencies
      pip: name="{{ item }}"
      with_items:
           - requests
           - base64

    - name: cluster api cluster_api_configuration tasks
      import_tasks: cluster_api_configuration.yml
      ignore_unreachable: true
    # -------------------------------------------------------------------------
    # ZABBIX API LOGIN
    - name: module api_login
      api_login:
        api_url:  "{{ api_url  }}"
        username: "{{ username }}"
        password: "{{ password }}"
      register: api_login

    - debug: var=api_login.appkey
    - name: export
      set_fact: appkey={{ api_login.appkey }}

     # -------------------------------------------------------------------------
     # ZABBIX API GET
    - name: module api_get_hostid
      api_get:
        select_key: "hostid"
        api_url:    "{{ api_url       }}"
        payload:    "{{ json_get_data }}"
      register: api_get

    - name: export
      set_fact:  api_get_hostid={{ api_get.value }}
    - debug: var=api_get_hostid

    - name: module api_get_tls_psk
      api_get:
        select_key: "tls_psk"
        api_url:    "{{ api_url       }}"
        payload:    "{{ json_get_data }}"
      register: api_get

    - name: export
      set_fact:  api_get_tls_psk={{ api_get.value }}
    - debug: var=api_get_tls_psk

    - name: module api_get_tls_psk_identity
      api_get:
        select_key: "tls_psk_identity"
        api_url:    "{{ api_url       }}"
        payload:    "{{ json_get_data }}"
      register: api_get

    - name: export
      set_fact:  api_get_tls_psk_identity={{ api_get.value }}
    - debug: var=api_get_tls_psk_identity
    # -------------------------------------------------------------------------
    # ZABBIX API POST
    - name: module api_post
      api_post:
        api_url:    "{{ api_url       }}"
        payload:    "{{ json_get_data }}"
      register: api_post

    # -------------------------------------------------------------------------
    # GATHER FACTS
    - debug: msg={{ ansible_default_ipv4.address }}
    - debug: msg={{ ansible_date_time.date }}

    # --------------------------------------------------------------------------
    # COMMAND LINE IMPUT VARIABLES
    # - debug: msg="{{ variable_test }}"
