---
- name: "Check if archiving is enabled for the domain = {{ item }}"
  command: mysql filter -N -e "select active from archive.options where domain='{{ item }}'"
  register: active
- debug: var=active.stdout

- name:  register domain name
  set_fact:
    domain_name: "{{ item }}"
- name: register logging_server
  set_fact:
     logging_server: "{{ hostvars['access.seinternal.com']['logging_filters'][domain_name] }}"
- debug: var=logging_server

- name: "Create remove_index script (purge the old archive index from the logging source_server)"
  template:
    src: templates/remove_index.py.j2
    dest: /tmp/remove_index.sh
    mode: "a+x"
- name: "Purge the old archive index from the logging source_server"
  command: python /tmp/remove_index.py
  when: logging_server == old_server and active.stdout == 1