---
- name: ensure groups exist
  group:
    name: "{{ item.name }}"
    state: present
    gid: "{{ item.gid | default(omit) }}"
  loop:  "{{ group_list }}"

- name: ensure users exist
  user:
    name:   "{{ item.1 }}"
    shell:  "{{ item.0.shell }}"
    groups: "{{ item.0.permission_group }}"
    append: yes
    state:  present
  loop: "{{ user_lists | subelements('users', 'skip_missing=True') }}"

- name: set authorized key for users
  authorized_key:
    user:  "{{ item.1 }}"
    state: present
    key:   "{{ lookup('file', 'user_keys/authorized_key.' + item.1 ) | default(omit) }}"
    manage_dir: False
  loop: "{{ user_lists | subelements('users', 'skip_missing=True') }}"

- name: sudoers.d templates
  template:
    src: "sudoers.j2"
    dest: "/etc/sudoers.d/{{ item.1 }}"
    validate: 'visudo -cf %s'
    mode: 0644
  loop: "{{ user_lists | subelements('users', 'skip_missing=True') }}"
