
# OUTGOING SUPPORT
# ------------------------------------------------------------------------------
- name: Check the SOCKS outgoing support for this server ipv4
  uri: url='https://localhost:30443/master/outgoing_ipv4_interfaces/?q={"fields":[{"field":"ip"}],"filters":[{"name":"ip", "op":"==", "val":"{{ item }}"}],"count":"true"}'
       validate_certs=false
  register: response

- name: Check for failure and output a message for SOCKS outgoing support for this server ipv4
  fail: msg="count != 0. Exiting gracefully ...."
  when: response.json.objects[0]['count'] != 0

- name: Check the SOCKS outgoing support for this server ipv6
  uri: url='https://localhost:30443/master/outgoing_ipv6_interfaces/?q={"fields":[{"field":"ip"}],"filters":[{"name":"ip", "op":"==", "val":"{{ item }}"}],"count":"true"}'
       validate_certs=false
  register: response

- name: Check for failure and output a message for SOCKS outgoing support for this server ipv6
  fail: msg="count != 0. Exiting gracefully ...."
  when: response.json.objects[0]['count'] != 0

  # INCOMING SUPPORT
  # ------------------------------------------------------------------------------
- name: Check the SOCKS incoming support for this server ipv4
  uri: url='https://localhost:30443/master/incoming_ipv4_interfaces/?q={"fields":[{"field":"ip"}],"filters":[{"name":"ip", "op":"==", "val":"{{ item }}"}],"count":"true"}'
       validate_certs=false
  register: response

- name: Check for failure and output a message for SOCKS incoming support for this server ipv4
  fail: msg="count != 0. Exiting gracefully ...."
  when: response.json.objects[0]['count'] != 0

- name: Check the SOCKS incoming support for this server ipv6
  uri: url='https://localhost:30443/master/incoming_ipv6_interfaces/?q={"fields":[{"field":"ip"}],"filters":[{"name":"ip", "op":"==", "val":"{{ item }}"}],"count":"true"}'
       validate_certs=false
  register: response

- name: Check for failure and output a message for SOCKS incoming support for this server ipv6
  fail: msg="count != 0. Exiting gracefully ...."
  when: response.json.objects[0]['count'] != 0
