---
- name: "check if the server role is {{ item }}"
  lineinfile:
    dest: /etc/spamexperts/cluster.conf
    line: "is_{{ item }} = True"
  check_mode: yes
  register: presence
  failed_when: presence.failed

- name: export
  set_fact:
      append_dict: "{ 'server_check_role is_{{ item }}' : 'True' }"
  when: not presence.changed
- name: export
  set_fact:
      append_dict: "{ 'server_check_role is_{{ item }}' : 'False' }"
  when:     presence.changed

- name: export
  set_fact:
      dict: "{{ dict | combine(append_dict) }}"
