---
- hosts: webservers
  become: True
  vars_files:
       group_vars/vars.yml
  vars:
       dict: {}
  tasks:
  - name: "Check the server roles"
    include: tasks/check_server_role.yml
    with_items:
      - quarantine
      - looping
      - archive

  # Step 1.b Check for the SOCKS support for this server on ansible_all_ipv4_addresses.
  - name: "Check socks support on this server"
    include: tasks/check_socks.yml
    with_nested:
      - "{{ ansible_all_ipv4_addresses }}"
      - "{{ ansible_all_ipv6_addresses }}"

  # Step 2. Check that the ipv4 of the server is not listed in the domains array.
  - name: "Check that server ipv4 address is not listed in the domains array"
    change_reports:
       domains:    "{{ domains }}"
       interfaces: "{{ ansible_all_ipv4_addresses }}"
    register: reports

  - name: export 1
    set_fact:
        dict: "{{ dict | combine(reports.value) }}"

  # Step 3. Check that the ipv6 of the server is not listed in the domains array.
  - name: "Check that server ipv6 address is not listed in the domains array"
    change_reports:
       domains:    "{{ domains }}"
       interfaces: "{{ ansible_all_ipv6_addresses }}"
    register: reports

  - name: export 2
    set_fact:
        dict: "{{ dict | combine(reports.value) }}"

  - debug: var=dict
