---
- import_playbook: ssh_authorize.yml
  vars:
    source: "{{ new_server }}"
    destination: "{{ old_server }}"

- hosts: "{{ new_server }}"
  become: true
  tasks:
    - name: "Run initial presync"
      shell: "rsync -e 'ssh -o StrictHostKeyChecking=no' -4 -av -H \
      --progress -i {{ old_server }}:/var/archive/ /var/archive/ --chown=Debian-exim:Debian-exim"

- hosts: localhost
  connection: local
  tasks:
    - name: "Get master server"
      get_servers_with_role:
        host: "{{ old_server }}"
        role: master
      register: master
    - debug: var=master

    - name: "Update archive storage node"
      uri: url="https://localhost:30443/master/archive/options/default/"
           method=POST return_content=yes HEADER_Content-Type="application/json"
           body="{{ storage_definition | to_json }}"
      delegate_to: "{{ master.meta[0] }}"

- hosts: "{{ new_server }}"
  become: true
  tasks:
    - name: "Run archive data sync"
      shell: "rsync -e 'ssh -o StrictHostKeyChecking=no' -4 -av -H \
      --progress -i {{ old_server }}:/var/archive/ /var/archive/ --chown=Debian-exim:Debian-exim"
