---
- hosts: management
  gather_facts: yes
  # become: True
  # become_method:  sudo
  #become_user:    root
  vars_files:
   group_vars/vars.yml
  tasks:
  # 1 - 3. Run api to update hostname confguration
  - name: "Change master server"
    change_server_roles:
      old_server: "{{ old_hostname }}"
      new_server: "{{ new_hostname }}"
      role: "master"
    register: output

  - name: "Change quarantine server"
    change_server_roles:
      old_server: "{{ old_hostname }}"
      new_server: "{{ new_hostname }}"
      role: "quarantine"
    register: output

  - name: "Change logging server"
    change_server_roles:
      old_server: "{{ old_hostname }}"
      new_server: "{{ new_hostname }}"
      role: "logging"
    register: output

  - name: "Change archive_master server"
    change_server_roles:
      old_server: "{{ old_hostname }}"
      new_server: "{{ new_hostname }}"
      role: "archive_master"
    register: output

  - name: "Change filter server"
    change_server_roles:
      old_server: "{{ old_hostname }}"
      new_server: "{{ new_hostname }}"
      role: "filter"
    register: output

  - name: "Get host groups list"
    get_host_groups:
      host: "{{ new_hostname }}"
    register: group_list
  - debug: var=group_list

  - name: "Get host templates list"
    get_host_templates:
      host: "{{ new_hostname }}"
    register: templates_list
  - debug: var=templates_list

  - name: "Update Host Group and Templates"
    local_action:
      module: zabbix_host
      server_url: https://monitor.seinternal.com
      login_user: "{{ username }}"
      login_password: "{{ password }}"
      host_name: "{{ new_hostname }}"
      visible_name:  "{{ new_hostname }}"
      host_groups: "{{ group_list.meta }}"
      link_templates: "{{ templates_list.meta }}"
      status: enabled
      state: present
      interfaces:
        - type: 1
          main: 1
          useip: 1
          ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
          dns: ""
          port: 10050
        - type: 4
          main: 1
          useip: 1
          ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
          dns: ""
          port: 12345

  - name: "Update Host Group and Templates"
    local_action:
      module: zabbix_host
      server_url: https://monitor.seinternal.com
      login_user: "{{ username }}"
      login_password: "{{ password }}"
      host_name: "{{ old_hostname }}"
      visible_name:  "{{ old_hostname }}"
      host_groups: "{{ group_list.meta }}"
      link_templates: "{{ templates_list.meta }}"
      status: enabled
      state: absent
      interfaces:
        - type: 1
          main: 1
          useip: 1
          ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
          dns: ""
          port: 10050
        - type: 4
          main: 1
          useip: 1
          ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
          dns: ""
          port: 12345

- hosts: webservers
  gather_facts: yes
  vars_files:
   group_vars/vars.yml

  tasks:
# Prerequisites for ansible run and python libraries
  - name: Install python-pip package
    become: true
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
    - python-pip

  - name: Install pip prerequisites
    pip:
      name: "{{ item }}"
    with_items:
    - requests
    - mysql-connector

# Replace the old host with new in the server
  - name: Replace old hostname
    replace:
      path: "{{ item }}"
      regexp: "{{ old_hostname }}"
      replace: "{{ new_hostname }}"
    with_items:
    - /etc/hostname
    - /etc/hosts
    - /root/salt_setup/pillar/data.sls
    - /etc/spamexperts/cluster.conf

# 5. Run the updater
  - name: Run the updater
    shell: "/home/spamexperts/update/update -d --skip-wait-turn --skip-version-check
    --skip-apt --skip-restart --skip-cron --skip-applications --skip-pip --skip-pip-cache --skip-preupdate
    --skip-postupdate --skip-salt --skip-preupdate-migrations --skip-postupdate-migrations"

# Adding scripts to current path
  - template:
      src:  "{{ item }}.j2"
      dest: /root/{{ item }}
      mode: 0777
    with_items:
      - update_mysql_filter.sql
      - master_script.py

# Run the mysql script
  - mysql_db:
      state: import
      name: all
      target: /root/update_mysql_filter.sql

# 10. Run python script to generate and update api user password for database using the new hostname as starting point
  - name: Running python script
    shell: python /root/master_script.py

# 11. Restart services so that the configuration loads with new hostname
  - name: Services restart
    service:
      name: "{{ item }}"
      state: restarted
    with_items:
      - exim4
      - pdns-recursor
      - exim4
      - exim4-outgoing
      - cron
      - zabbix-agent
      - dovecot
      - nginx
      - watch_imap
