---
- hosts: webservers
  vars_files:
   group_vars/vars.yml

  tasks:

  # Login in api and retrieve the api key
  - name: Login to API and retrieve the auth key
    api_login:
      api_url: "https://monitor.seinternal.com/api_jsonrpc.php"
      username: "{{ username }}"
      password: "{{ password }}"
      username_auth: "{{ username_auth }}"
      password_auth: "{{ password_auth }}"
    register: api_login


  # - name: Get {{ new_hostname }} hostid key value using api module
  #   get_api:
  #     api_url: "{{ apiurl }}"
  #     api_key: "{{ api_login.id }}"
  #     select_key: "{{ new_hostname }}"
  #     payload: "{{ json_data }}"
  #
  # - name: Get {{ tls_psk_key }} key value using api module
  #   get_api:
  #     api_url: "{{ apiurl }}"
  #     api_key: "{{ api_login.id }}"
  #     select_key: "tls_psk_key"
  #     payload: "{{ json_data }}"
  #
  # - name: Post a change into zabbix api
  #   post_api:
  #     api_url: "{{api_url}}"
  #     api_key: "{{ api_login.id }}"
  #     json_data: "{{ json_post_data }}"


  # - name: Post requests to change the name of the server in zabbix
  #   post_api:
  #     json_data: json_data
  #     api_url: api_url
  #     api_key_auth: api_login.id
  #     hostid: "1234567890"
