---
- name:  "register domain name"
  set_fact:
    domain_name: "{{ item }}"
- name: "register table name (depends on domain name)"
  set_fact:
    table: "{{ domain_name | replace('.','_') | replace('-','@002d') }}"

- name: register logging_server
  set_fact:
     logging_server: "{{ hostvars['access.seinternal.com']['logging_filters'][domain_name] }}"
- debug: var=logging_server

# VERIFICATION
# -------------------------------------------------------------------------------------------------------------
- name: "mysql check table base existence on mx_messages"
  command: mysql -e "SHOW TABLES LIKE '{{ table }}';" "mx_messages"
  register: existence_table_on_mx_messages

- name: "mysql check table existence on mx_messages_outgoing"
  command: mysql -e "SHOW TABLES LIKE '{{ table }}';" "mx_messages_outgoing"
  register: existence_table_on_mx_messages_outgoing

- name: "mysql check old_{{ table }} base existence on mx_messages"
  command: mysql -e "SHOW TABLES LIKE 'old_{{ table }}';" "mx_messages"
  register: existence_old_table_on_mx_messages

- name: "mysql check old_{{ table }} existence on mx_messages_outgoing"
  command: mysql -e "SHOW TABLES LIKE 'old_{{ table }}';" "mx_messages_outgoing"
  register: existence_old_table_on_mx_messages_outgoing
# -------------------------------------------------------------------------------------------------------------

# - name: "mysql lock table {{ table }} for domain {{ domain_name }} on mx_messages"
#   command: mysql -e "LOCK TABLE mx_messages.{{ table }} READ;"
#   when: logging_server == old_server and existence_table_on_mx_messages.stdout != ''
#
# - name: "mysql lock table {{ table }} for domain {{ domain_name }} on mx_messages_outgoing"
#   command: mysql -e "LOCK TABLE mx_messages.{{ table }} READ;"
#   when: logging_server == old_server and existence_table_on_mx_messages_outgoing.stdout != ''

- name: "mysql rename table mx_messages.{{ table }} for domain {{ domain_name }}"
  command: mysql -e "RENAME TABLE  mx_messages.{{ table }} TO  mx_messages.old_{{ table }};"
  when: logging_server == old_server and existence_table_on_mx_messages.stdout != '' and existence_old_table_on_mx_messages.stdout == ''

- name: "mysql rename table mx_messages_outgoing.{{ table }} for domain {{ domain_name }}"
  command: mysql -e "RENAME TABLE  mx_messages_outgoing.{{ table }} TO  mx_messages_outgoing.old_{{ table }};"
  when: logging_server == old_server and existence_table_on_mx_messages_outgoing.stdout != '' and existence_old_table_on_mx_messages_outgoing.stdout == ''
