---
- uri:
    url: "https://{{ master.meta[0] }}:30443/master/archive/options/{{ item }}/active"
    method: GET
    status_code: [200,404]
    validate_certs: no
  register: active_status
  delegate_to: "{{ master.meta[0] }}"

- name: "register archive options dictionaries when status == 200"
  set_fact:
      archive_options: "{{ archive_options | combine({ item: active_status.json.active }) }}"
  when: active_status.status == 200

- name: "register archive options dictionaries when status != 200"
  set_fact:
      archive_options: "{{ archive_options | combine({ item: 0 }) }}"
  when: active_status.status != 200
