---
- hosts: webservers
  become: True
  vars_files:
       group_vars/vars.yml
  vars:
        dict:                {}
        dict_support_report: {}
  tasks:
  - name: export
    set_fact:
        append_dict: "{'server_check hostname': '{{inventory_hostname}}'}"
  - name: export
    set_fact:
        dict:                "{{ dict | combine(append_dict) }}"
        dict_support_report: "{{ dict_support_report | combine(append_dict) }}"

  - name: "Check the server roles"
    include: tasks/check_server_role.yml
    with_items:
      - quarantine
      - looping
      - archive

  # Step 1.b Check for the SOCKS support for this server on ansible_all_ipv4_addresses.
  - name: "Check socks support on this server"
    include: tasks/check_socks.yml
    with_nested:
      - "{{ ansible_all_ipv4_addresses }}"
      - "{{ ansible_all_ipv6_addresses }}"

  # Step 2. Check that the ipv4 of the server is not listed in the domains array.
  - name: "Check that server ipv4 address is not listed in the domains array"
    include: tasks/server_check_ipv4.yml
    with_nested:
      - "{{ domains }}"
      - "{{ ansible_all_ipv4_addresses }}"

  # Step 3. Check that the ipv6 of the server is not listed in the domains array.
  - name: "Check that server ipv6 address is not listed in the domains array"
    include: tasks/server_check_ipv6.yml
    with_nested:
      - "{{ domains }}"
      - "{{ ansible_all_ipv6_addresses }}"

  - debug: msg="{{ dict }}"
  - debug: msg="{{ dict_support_report }}"
