---
- hosts: webservers
  become: True
  vars_files:
       group_vars/vars.yml
  tasks:
  # Step 1. Ensure the server does not have a special role
  # Step 1.a  Check that the server does not have roles for quarantine,logging, archiving, backup
  - name: "Check the server roles"
    include: tasks/check_server_role.yml
    with_items:
      - quarantine
      - looping
      - archive

  # Step 1.b Check for the SOCKS support for this server on ansible_all_ipv4_addresses.
  - name: "Check socks support on this server"
    include: tasks/check_socks.yml
    with_nested:
      - "{{ ansible_all_ipv4_addresses }}"

  # Step 2. Check that the ipv4 of the server is not listed in the domains array.
  - name: "Check socks support on this server"
    include: tasks/server_check_ipv4.yml
    with_nested:
      - "{{ domains }}"
      - "{{ ansible_all_ipv4_addresses }}"

  # Step 3. Check that the ipv6 of the server is not listed in the domains array.
  - name: "Check socks support on this server"
    include: tasks/server_check_ipv6.yml
    with_nested:
      - "{{ domains }}"
      - "{{ ansible_all_ipv6_addresses }}"
